app:
    resource: "@AppBundle/Controller/App"
    host:     "www.mall.com"
    type:     annotation
admin:
  resource: "@AppBundle/Controller/Admin"
  host:     "admin.mall.com"
  type:     annotation